version: "3"
volumes:
  public:
services:
  nginx:
    image: nginx:latest
    ports:
      - 9002:80
    volumes:
        - ${PWD}/nginx-logs:/var/log/nginx
        - public:/app/public
        - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
    command: [nginx-debug, '-g', 'daemon off;']
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    env_file:
      - .env
    environment:
      APP_ENV: production
      APP_SUBPATH: "/project-subpath"
      ASSET_URL: "https://telotawebdev.bbaw.de/project-subpath"
      APP_URL: "https://telotawebdev.bbaw.de/project-subpath"
      DB_CONNECTION: sqlite
      DB_DATABASE: /app/users.sqlite
      WEBDAV_BASE_URI: "/project-subpath/webdav"
      WEBDAV_DATA: "/path/to/data"
      LOG_CHANNEL: daily
      LOG_LEVEL: info
    volumes:
      - public:/app/public
      - ./storage/logs:/app/storage/logs
      - ${PWD}/users.sqlite:/app/users.sqlite
